# Generated by Django 5.2.12 on 2026-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
    ]
